'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
function createRegistry({env=process.env,folder=__dirname,protect=dpapi}={}) {
 const file=path.join(folder,'connections.private.json'); const defaults=[];
 if(env.MCP_ENDPOINT)defaults.push({id:'xiyou-default',provider:'xiyou',name:'西柚 A',endpoint:env.MCP_ENDPOINT,key:env.MCP_API_KEY||'',authHeader:env.MCP_AUTH_HEADER||'Authorization',authPrefix:env.MCP_AUTH_PREFIX??'Bearer ',enabled:true});
 if(env.SELLER_MCP_ENDPOINT)defaults.push({id:'seller-default',provider:'sellersprite',name:'卖家精灵 A',endpoint:env.SELLER_MCP_ENDPOINT,key:env.SELLER_MCP_KEY||'',authHeader:env.SELLER_MCP_HEADER||'secret-key',authPrefix:'',enabled:true});
 let state={connections:defaults}; if(fs.existsSync(file))state=JSON.parse(protect('open',fs.readFileSync(file,'utf8')));
 const list=()=>state.connections.map(c=>({id:c.id,provider:c.provider,name:c.name,enabled:c.enabled,host:new URL(c.endpoint).host,authHeader:c.authHeader,authPrefix:c.authPrefix,hasKey:!!c.key}));
 function persist(next){const sealed=protect('seal',JSON.stringify(next));fs.writeFileSync(file+'.tmp',sealed,{mode:0o600});fs.renameSync(file+'.tmp',file);state=next;}
 function update(action){const next=structuredClone(state),arr=next.connections;
  if(action.action==='save'){const input=action.connection||{},old=arr.find(c=>c.id===input.id);if(input.id&&!old)throw Error('连接不存在');const c={id:old?.id||crypto.randomUUID(),provider:input.provider||old?.provider,name:String(input.name||old?.name||'').trim(),endpoint:input.endpoint||old?.endpoint,key:input.key||old?.key||'',authHeader:input.authHeader||old?.authHeader||'Authorization',authPrefix:input.authPrefix??old?.authPrefix??'Bearer ',enabled:old?.enabled??true};if(!['xiyou','sellersprite'].includes(c.provider)||!c.name||c.name.length>80)throw Error('请填写连接名称和平台');const url=new URL(c.endpoint);if(url.protocol!=='https:'||url.username||url.password||url.hash)throw Error('MCP 地址须为 HTTPS，不接受用户名密码或片段');if(old&&new URL(old.endpoint).origin!==url.origin&&!input.key)throw Error('更换服务地址时请重新填写该服务的密钥，不能自动沿用旧密钥');if(!/^[a-zA-Z0-9-]+$/.test(c.authHeader)||/^(host|origin|content-length|content-type|connection|cookie)$/i.test(c.authHeader)||/[\r\n]/.test(c.key+c.authPrefix))throw Error('鉴权配置无效');if(old)arr[arr.indexOf(old)]=c;else arr.push(c);
  }else if(action.action==='toggle'){const c=arr.find(c=>c.id===action.id);if(!c)throw Error('连接不存在');c.enabled=!c.enabled;}else if(action.action==='move'){const i=arr.findIndex(c=>c.id===action.id);if(i<0)throw Error('连接不存在');const indices=arr.map((c,j)=>c.provider===arr[i].provider?j:-1).filter(j=>j>=0);const j=indices[indices.indexOf(i)+(action.direction==='up'?-1:1)];if(j!==undefined)[arr[i],arr[j]]=[arr[j],arr[i]];}else throw Error('不支持的操作');persist(next);return list();}
 return {list,update,get:id=>state.connections.find(c=>c.id===id&&c.enabled)};
}
function dpapi(mode,value){const code=mode==='seal'?"$s=[Console]::In.ReadToEnd();$b=[Text.Encoding]::UTF8.GetBytes($s);[Convert]::ToBase64String([Security.Cryptography.ProtectedData]::Protect($b,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser))":"$s=[Console]::In.ReadToEnd();$b=[Convert]::FromBase64String($s);[Text.Encoding]::UTF8.GetString([Security.Cryptography.ProtectedData]::Unprotect($b,$null,[Security.Cryptography.DataProtectionScope]::CurrentUser))";return cp.execFileSync('C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',['-NoProfile','-Command','Add-Type -AssemblyName System.Security;'+code],{input:value,encoding:'utf8',windowsHide:true,stdio:['pipe','pipe','pipe']}).trim();}
module.exports={createRegistry};
