/**
 * 生成 GitHub Pages 静态站点到 docs/（CI 友好：bundle 可选）
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const out = path.join(root, "docs");
const isWin = process.platform === "win32";

function rmrf(dir) {
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
}

function mkdirp(p) {
  fs.mkdirSync(p, { recursive: true });
}

function copyFile(src, dest) {
  if (!fs.existsSync(src)) {
    console.warn("skip (missing):", path.relative(root, src));
    return false;
  }
  mkdirp(path.dirname(dest));
  fs.copyFileSync(src, dest);
  return true;
}

function copyDir(src, dest) {
  if (!fs.existsSync(src)) {
    console.warn("skip dir (missing):", path.relative(root, src));
    return;
  }
  mkdirp(dest);
  for (const name of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, name.name);
    const d = path.join(dest, name.name);
    if (name.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function run(cmd, opts = {}) {
  execSync(cmd, { cwd: root, stdio: "inherit", ...opts });
}

function getCiGistSecrets() {
  const token = (process.env.GITHUB_GIST_TOKEN || process.env.OPS_GIST_TOKEN || "").trim();
  const gistId = (process.env.GITHUB_GIST_ID || process.env.OPS_GIST_ID || "").trim();
  if (token && gistId) return { token, gistId };
  const cfgPath = path.join(root, "src", "cloud-sync-config.js");
  if (fs.existsSync(cfgPath)) {
    const src = fs.readFileSync(cfgPath, "utf8");
    const id = (src.match(/GITHUB_GIST_ID\s*=\s*"([^"]*)"/) || [])[1]?.trim();
    if (token && id) return { token, gistId: id };
  }
  return null;
}

console.log("==> sync browser jsx");
run("node sync-browser.mjs");

console.log("==> sync amazon news (optional)");
try {
  run("node sync-amazon-news.mjs --force");
} catch {
  console.warn("amazon-news sync skipped");
}

console.log("==> build precompiled app.bundle.js (optional)");
try {
  if (fs.existsSync(path.join(root, "node_modules", "@babel/standalone"))) {
    run("node deploy/build-browser-bundle.mjs");
  } else {
    run("npm ci --no-audit --no-fund");
    run("node deploy/build-browser-bundle.mjs");
  }
} catch (e) {
  console.warn("bundle build skipped:", e?.message || e);
}

const bundlePath = path.join(root, "app.bundle.js");
if (fs.existsSync(bundlePath)) {
  const bundle = fs.readFileSync(bundlePath, "utf8");
  const gistOk = bundle.includes("GITHUB_GIST_ID") && bundle.includes("api.github.com/gists");
  if (!gistOk || bundle.includes("key: configVersion")) {
    console.warn("bundle outdated — Pages will use runtime .browser.jsx instead");
    fs.unlinkSync(bundlePath);
  }
}

if (isWin) {
  console.log("==> pack optional zips (windows only)");
  for (const script of ["deploy/pack-disk-cleaner.ps1", "deploy/pack-mailwatch.ps1"]) {
    try {
      run(`powershell -NoProfile -ExecutionPolicy Bypass -File "${script}"`);
    } catch {
      console.warn(`skipped ${script}`);
    }
  }
}

console.log("==> build docs/");
rmrf(out);
mkdirp(out);

console.log("==> sync cloud snapshots (Pages fallback for CN)");
try {
  run("node deploy/sync-cloud-snapshot.mjs");
} catch (e) {
  console.warn("cloud snapshot skipped:", e?.message || e);
}

const staticFiles = [
  "app.html",
  "gist-config.js",
  "logo.svg",
  "fx-rates.json",
  "amazon-news.json",
  "fba-profit-calculator.html",
  "fba-warehouse-tool.html",
];

for (const f of staticFiles) {
  copyFile(path.join(root, f), path.join(out, f));
}

const ciGist = getCiGistSecrets();
if (ciGist) {
  const gistCfg =
    "window.__OPS_GIST__ = window.__OPS_GIST__ || {};\n" +
    `window.__OPS_GIST__.token = ${JSON.stringify(ciGist.token)};\n` +
    `window.__OPS_GIST__.id = ${JSON.stringify(ciGist.gistId)};\n`;
  fs.writeFileSync(path.join(out, "gist-config.js"), gistCfg, "utf8");
  console.log("gist-config.js ← CI secrets (deploy only, not in git)");
} else {
  copyFile(path.join(root, "gist-config.js"), path.join(out, "gist-config.js"));
}

if (fs.existsSync(bundlePath)) {
  copyFile(bundlePath, path.join(out, "app.bundle.js"));
}

copyFile(path.join(root, "app.html"), path.join(out, "index.html"));

for (const f of fs.readdirSync(path.join(root, "src")).filter(n => n.endsWith(".browser.jsx"))) {
  copyFile(path.join(root, "src", f), path.join(out, "src", f));
}

copyDir(path.join(root, "tools"), path.join(out, "tools"));
copyDir(path.join(root, "packages"), path.join(out, "packages"));

fs.writeFileSync(path.join(out, ".nojekyll"), "");
fs.writeFileSync(
  path.join(out, "README.txt"),
  "Generated by deploy/build-pages.mjs — do not edit by hand.\n"
);

console.log("\nDone:", out);
